# $schema: ../schema.json
name: $sqrt
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sqrt/'
type:
    - resolvesToDouble
encode: single
description: |
    Calculates the square root.
arguments:
    -
        name: number
        type:
            - resolvesToNumber
        description: |
            The argument can be any valid expression as long as it resolves to a non-negative number.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sqrt/#example'
        pipeline:
            -
                $project:
                    distance:
                        $sqrt:
                            $add:
                                -
                                    $pow:
                                        -
                                            $subtract:
                                                - '$p2.y'
                                                - '$p1.y'
                                        - 2
                                -
                                    $pow:
                                        -
                                            $subtract:
                                                - '$p2.x'
                                                - '$p1.x'
                                        - 2
