- name: match
  type: stage
  args:
    - name: query
      type: expression
- name: sort
  type: stage
  args:
    - name: sortSpecification
      type: number # should be an enum PHPLIB-1269
      isVariadic: true
- name: limit
  type: stage
  args:
    - name: limit
      type: resolvesToInt
- name: group
  type: stage
  encode: object
  args:
    - name: _id
      type: [expression, "null"]
    - name: fields
      type: expression
      isVariadic: true
      variadicMin: 0
- name: project
  type: stage
  args:
    - name: specifications
      type: expression
      isVariadic: true
