# $schema: ../schema.json
name: $planCacheStats
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/planCacheStats/'
type:
    - Stage
encode: object
description: |
    Returns plan cache information for a collection.
