# $schema: ../schema.json
name: $replaceWith
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceWith/'
type:
    - Stage
encode: single
description: |
    Replaces a document with the specified embedded document. The operation replaces all existing fields in the input document, including the _id field. Specify a document embedded in the input document to promote the embedded document to the top level.
    Alias for $replaceRoot.
arguments:
    -
        name: expression
        type:
            - resolvesToObject
