# $schema: ../schema.json
name: $sort
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/sort/'
type:
    - Stage
encode: single
description: |
    Reorders the document stream by a specified sort key. Only the order changes; the documents remain unmodified. For each input document, outputs one document.
arguments:
    -
        name: sort
        type:
            - SortSpec
