# $schema: ../schema.json
name: $unwind
category:
    - Stage
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/'
type:
    - Stage
encode: object
description: |
    Deconstructs an array field from the input documents to output a document for each element. Each output document replaces the array with an element value. For each input document, outputs n documents where n is the number of array elements and can be zero for an empty array.
arguments:
    -
        name: field
        type:
            - ArrayFieldPath
