#
# Build variants to build the driver - these are run for all operating systems and PHP versions we support
#
buildvariants:
  # Debian
  - name: build-debian12
    display_name: "Build: Debian 12"
    tags: ["build", "debian", "x64"]
    run_on: debian12-small
    tasks:
      - name: "build-all-php"
  - name: build-debian11
    display_name: "Build: Debian 11"
    tags: ["build", "debian", "x64", "pr", "tag"]
    run_on: debian11-small
    tasks:
      - name: "build-all-php"

  # RHEL
  - name: build-rhel90
    display_name: "Build: RHEL 9.0"
    tags: ["build", "rhel", "x64", "pr", "tag"]
    run_on: rhel90-small
    tasks:
      - name: "build-all-php"
  - name: build-rhel9-zseries
    display_name: "Build: RHEL 9 Zseries"
    tags: ["build", "rhel", "zseries", "tag"]
    run_on: rhel9-zseries-small
    tasks:
      - name: "build-all-php"
  - name: build-rhel9-power
    display_name: "Build: RHEL 9 PPC"
    tags: ["build", "rhel", "power", "tag"]
    run_on: rhel9-power-small
    tasks:
      - name: "build-all-php"
  - name: build-rhel82-arm64
    display_name: "Build: RHEL 8.2 ARM64"
    tags: ["build", "rhel", "arm64", "tag"]
    run_on: rhel82-arm64
    tasks:
      - name: "build-all-php"
  - name: build-rhel80
    display_name: "Build: RHEL 8.0"
    tags: ["build", "rhel", "x64", "pr", "tag"]
    run_on: rhel80-small
    tasks:
      - name: "build-all-php"

  # Ubuntu LTS
  - name: build-ubuntu2204
    display_name: "Build: Ubuntu 22.04 x64"
    tags: ["build", "ubuntu", "x64", "pr", "tag"]
    run_on: ubuntu2204-small
    tasks:
      - name: "build-all-php"
  - name: build-ubuntu2204-arm64
    display_name: "Build: Ubuntu 22.04 ARM64"
    tags: ["build", "ubuntu", "arm64", "tag"]
    run_on: ubuntu2204-arm64-small
    tasks:
      - name: "build-all-php"
  - name: build-ubuntu2004
    display_name: "Build: Ubuntu 20.04 x64"
    tags: ["build", "ubuntu", "x64", "pr", "tag"]
    run_on: ubuntu2004-small
    tasks:
      - name: "build-all-php"
  - name: build-ubuntu2004-arm64
    display_name: "Build: Ubuntu 20.04 ARM64"
    tags: ["build", "ubuntu", "arm64", "tag"]
    run_on: ubuntu2004-arm64-small
    tasks:
      - name: "build-all-php"
