axes:
  # Note: install-dependencies.sh will search for the latest minor version
  # matching the PHP_VERSION constant
  - id: php-versions
    display_name: PHP Version
    values:
      - id: "8.2"
        display_name: "PHP 8.2"
        variables:
          PHP_VERSION: "8.2"
      - id: "8.1"
        display_name: "PHP 8.1"
        variables:
          PHP_VERSION: "8.1"
      - id: "8.0"
        display_name: "PHP 8.0"
        variables:
          PHP_VERSION: "8.0"
      - id: "7.4"
        display_name: "PHP 7.4"
        variables:
          PHP_VERSION: "7.4"

  - id: mongodb-versions
    display_name: MongoDB Version
    values:
      - id: "latest"
        display_name: "MongoDB latest"
        variables:
          MONGODB_VERSION: "latest"
      - id: "rapid"
        display_name: "MongoDB rapid"
        variables:
          MONGODB_VERSION: "rapid"
      - id: "7.0"
        display_name: "MongoDB 7.0"
        variables:
          MONGODB_VERSION: "7.0"
      - id: "6.0"
        display_name: "MongoDB 6.0"
        variables:
          MONGODB_VERSION: "6.0"
      - id: "5.0"
        display_name: "MongoDB 5.0"
        variables:
          MONGODB_VERSION: "5.0"
      - id: "4.4"
        display_name: "MongoDB 4.4"
        variables:
          MONGODB_VERSION: "4.4"
      - id: "4.2"
        display_name: "MongoDB 4.2"
        variables:
          MONGODB_VERSION: "4.2"
      - id: "4.0"
        display_name: "MongoDB 4.0"
        variables:
          MONGODB_VERSION: "4.0"
      - id: "3.6"
        display_name: "MongoDB 3.6"
        variables:
          MONGODB_VERSION: "3.6"

  - id: driver-versions
    display_name: Driver Version
    values:
      - id: "oldest-supported"
        display_name: "PHPC 1.17.0"
        variables:
          EXTENSION_BRANCH: "master"
      - id: "latest-stable"
        display_name: "PHPC (1.17.x)"
        variables:
          EXTENSION_BRANCH: "master"
      - id: "latest-dev"
        display_name: "PHPC (1.17-dev)"
        variables:
          EXTENSION_BRANCH: "master"

  - id: dependencies
    display_name: Dependencies
    values:
      - id: lowest
        display_name: Lowest
        variables:
          DEPENDENCIES: "lowest"

buildvariants:
  # Test oldest-supported PHP, MongoDB, and driver versions with lowest dependencies on Debian
  - matrix_name: "test-oldest-supported"
    matrix_spec: { "os": "debian92", "mongodb-edge-versions": "oldest-supported", "php-edge-versions": "oldest-supported", "driver-versions": "oldest-supported", "dependencies": "lowest" }
    display_name: "Lowest Dependencies: ${os}, ${mongodb-edge-versions}, ${php-edge-versions}, ${driver-versions}"
    tasks:
      - name: "test-standalone"
      - name: "test-replica_set"
      - name: "test-sharded_cluster"
