tasks:
  - name: "test-atlas-data-lake"
    commands:
      - func: "bootstrap mongohoused"
      - func: "run atlas data lake test"

  - name: "test-csfle-crypt_shared"
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "replica_set"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          TESTS: "csfle"

  - name: "test-csfle-mongocryptd"
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "replica_set"
          SKIP_CRYPT_SHARED: "yes"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          TESTS: "csfle"

  - name: "test-without_aws_creds"
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "replica_set"
      - func: "start kms servers"
      - func: "run tests"
        vars:
          client_side_encryption_aws_access_key_id: ""
          client_side_encryption_aws_secret_access_key: ""
          TESTS: "csfle-without-aws-creds"
