axes:
  # Note: install-dependencies.sh will search for the latest minor version
  # matching the PHP_VERSION constant
  - id: php-versions
    display_name: PHP Version
    values:
      - id: "8.2"
        display_name: "PHP 8.2"
        variables:
          PHP_VERSION: "8.2"
      - id: "8.1"
        display_name: "PHP 8.1"
        variables:
          PHP_VERSION: "8.1"
      - id: "8.0"
        display_name: "PHP 8.0"
        variables:
          PHP_VERSION: "8.0"
      - id: "7.4"
        display_name: "PHP 7.4"
        variables:
          PHP_VERSION: "7.4"

  - id: mongodb-versions
    display_name: MongoDB Version
    values:
      - id: "latest"
        display_name: "MongoDB latest"
        variables:
          MONGODB_VERSION: "latest"
      - id: "rapid"
        display_name: "MongoDB rapid"
        variables:
          MONGODB_VERSION: "rapid"
      - id: "7.0"
        display_name: "MongoDB 7.0"
        variables:
          MONGODB_VERSION: "7.0"
      - id: "6.0"
        display_name: "MongoDB 6.0"
        variables:
          MONGODB_VERSION: "6.0"
      - id: "5.0"
        display_name: "MongoDB 5.0"
        variables:
          MONGODB_VERSION: "5.0"
      - id: "4.4"
        display_name: "MongoDB 4.4"
        variables:
          MONGODB_VERSION: "4.4"
      - id: "4.2"
        display_name: "MongoDB 4.2"
        variables:
          MONGODB_VERSION: "4.2"
      - id: "4.0"
        display_name: "MongoDB 4.0"
        variables:
          MONGODB_VERSION: "4.0"
      - id: "3.6"
        display_name: "MongoDB 3.6"
        variables:
          MONGODB_VERSION: "3.6"

  - id: driver-versions
    display_name: Driver Version
    values:
      - id: "oldest-supported"
        display_name: "PHPC 1.17.0"
        variables:
          EXTENSION_BRANCH: "master"
      - id: "latest-stable"
        display_name: "PHPC (1.17.x)"
        variables:
          EXTENSION_BRANCH: "master"
      - id: "latest-dev"
        display_name: "PHPC (1.17-dev)"
        variables:
          EXTENSION_BRANCH: "master"

  - id: dependencies
    display_name: Dependencies
    values:
      - id: lowest
        display_name: Lowest
        variables:
          DEPENDENCIES: "lowest"

buildvariants:
  # Test oldest-supported PHP, MongoDB, and driver versions with lowest dependencies on Debian
  - matrix_name: "test-oldest-supported"
    matrix_spec: { "os": "debian92", "mongodb-edge-versions": "oldest-supported", "php-edge-versions": "oldest-supported", "driver-versions": "oldest-supported", "dependencies": "lowest" }
    display_name: "Lowest Dependencies: ${os}, ${mongodb-edge-versions}, ${php-edge-versions}, ${driver-versions}"
    tasks:
      - name: "test-standalone"
      - name: "test-replica_set"
      - name: "test-sharded_cluster"

  - matrix_name: "atlas-data-lake-test"
    matrix_spec: { "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    display_name: "Atlas Data Lake"
    run_on: debian11
    expansions:
      VARIANT: debian11 # Referenced by ADL build script for downloading MQLRun
    tasks:
      - name: "test-atlas-data-lake"

  - matrix_name: "test-requireApiVersion"
    matrix_spec: { "os": "debian11", "mongodb-versions": "*", "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    display_name: "Versioned API - ${mongodb-versions}"
    exclude_spec:
      # Stable API is available from MongoDB 5.0+
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4"], "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    tasks:
      - .versioned-api

  - matrix_name: "serverless"
    matrix_spec: { "os": "debian11", "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    display_name: "Serverless"
    tasks:
      - .serverless

  - matrix_name: "test-loadBalanced"
    matrix_spec: { "os": "debian11", "mongodb-versions": "*", "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    display_name: "Load balanced - ${mongodb-versions}"
    exclude_spec:
      # Load balancer is available from MongoDB 5.0+
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4"], "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    tasks:
      - name: "test-loadBalanced"

  # CSFLE tests (crypt_shared and mongocryptd) are tested on RHEL 8 as it's the only version that supports
  # 4.2 AND 6.0 (which is required for crypt_shared), as well as a somewhat relevant PHP version.
  # Newer MongoDB version may require adding different operating systems here
  - matrix_name: "test-csfle-crypt_shared"
    matrix_spec: { "os": "rhel80", "mongodb-versions": "*", "php-versions": "8.0", "driver-versions": "latest-stable" }
    display_name: "CSFLE crypt_shared - ${mongodb-versions}"
    exclude_spec:
      # MongoDB < 4.2 does not need to be tested.
      - { "os": "rhel80", "mongodb-versions": ["3.6", "4.0"], "php-versions": "8.0", "driver-versions": "latest-stable" }
    tasks:
      - name: "test-csfle-crypt_shared"
  - matrix_name: "test-csfle-mongocryptd"
    matrix_spec: { "os": "rhel80", "mongodb-versions": "*", "php-versions": "8.0", "driver-versions": "latest-stable" }
    display_name: "CSFLE mongocryptd - ${mongodb-versions}"
    exclude_spec:
      # MongoDB < 4.2 does not need to be tested.
      - { "os": "rhel80", "mongodb-versions": ["3.6", "4.0"], "php-versions": "8.0", "driver-versions": "latest-stable" }
    tasks:
      - name: "test-csfle-mongocryptd"

  # Run CSFLE tests without AWS credentials (for "On-demand AWS Credentials" prose test)
  - matrix_name: "test-csfle-without_aws_creds"
    matrix_spec: { "os": ["debian92", "debian11"], "mongodb-versions": "*", "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    display_name: "CSFLE without_aws_creds - ${mongodb-versions}"
    exclude_spec:
      # CSFLE is available from MongoDB 4.2+ and Debian 9.2 only supports up to MongoDB 5.0
      - { "os": "debian92", "mongodb-versions": ["3.6", "4.0", "6.0", "rapid", "latest"], "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
      - { "os": "debian11", "mongodb-versions": ["3.6", "4.0", "4.2", "4.4", "5.0"], "php-edge-versions": "latest-stable", "driver-versions": "latest-stable" }
    tasks:
      - name: "test-without_aws_creds"
