tasks:
  - name: "test-atlas-data-lake"
    commands:
      - func: "bootstrap mongohoused"
      - func: "run atlas data lake test"

  - name: "test-requireApiVersion"
    tags: ["versioned-api"]
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          AUTH: "auth"
          REQUIRE_API_VERSION: "yes"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          API_VERSION: "1"

  - name: "test-acceptApiVersion2"
    tags: ["versioned-api"]
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "server"
          ORCHESTRATION_FILE: "versioned-api-testing.json"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          TESTS: "versioned-api"

  - name: "test-serverless"
    tags: ["serverless"]
    commands:
      - func: "create serverless instance"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run serverless tests"

  - name: "test-loadBalanced"
    tags: ["loadbalanced"]
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "sharded_cluster"
          LOAD_BALANCER: "true"
          SSL: "yes"
      - func: "start load balancer"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          # Note: loadBalanced=true should already be appended to SINGLE_MONGOS_LB_URI
          MONGODB_URI: "${SINGLE_MONGOS_LB_URI}"
          SSL: "yes"
      # Note: "stop load balancer" will be called from "post"

  - name: "test-csfle-crypt_shared"
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "replica_set"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          TESTS: "csfle"

  - name: "test-csfle-mongocryptd"
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "replica_set"
          SKIP_CRYPT_SHARED: "yes"
      - func: "start kms servers"
      - func: "set aws temp creds"
      - func: "run tests"
        vars:
          TESTS: "csfle"

  - name: "test-without_aws_creds"
    commands:
      - func: "bootstrap mongo-orchestration"
        vars:
          TOPOLOGY: "replica_set"
      - func: "start kms servers"
      - func: "run tests"
        vars:
          client_side_encryption_aws_access_key_id: ""
          client_side_encryption_aws_secret_access_key: ""
          TESTS: "csfle-without-aws-creds"
