buildvariants:
  # Run benchmarks
  - name: benchmark-rhel90
    tags: ["benchmark", "rhel", "x64"]
    display_name: "Benchmark: RHEL 9.0, MongoDB 6.0"
    run_on: rhel90-dbx-perf-large
    expansions:
      FETCH_BUILD_VARIANT: "build-rhel90"
      FETCH_BUILD_TASK: "build-php-8.2"
      PHP_VERSION: "8.2"
    depends_on:
      - variant: "build-rhel90"
        name: "build-php-8.2"
    tasks:
      - "run-benchmark"

  # Run Atlas Data Lake Tests on Ubuntu
  - name: test-ubuntu2204-php82-local
    tags: ["test", "ubuntu", "x64"]
    display_name: "Test: Ubuntu 22.04 x64, PHP 8.2"
    run_on: ubuntu2204-small
    expansions:
      FETCH_BUILD_VARIANT: "build-ubuntu2204"
      FETCH_BUILD_TASK: "build-php-8.2"
      PHP_VERSION: "8.2"
    depends_on:
      - variant: "build-ubuntu2204"
        name: "build-php-8.2"
    tasks:
      - "test-atlas-data-lake"
