# When a task that used to pass starts to fail, go through all versions that may have been skipped to detect when the
# task started failing.
stepback: true

# Mark a failure as a system/bootstrap failure (purple box) rather than a task failure by default.
# Actual testing tasks are marked with `type: test`
command_type: system

# Fail builds when pre tasks fail.
pre_error_fails_task: true

# Protect ourselves against rogue test case that runs forever
# Good rule of thumb: the average length a task takes, times 5, which roughly accounts for variable system performance
# for various build variants
exec_timeout_secs: 1800

# These pre and post rules apply to all tasks not part of a task group, which should only ever be tests against local
# MongoDB instances. All other tasks that require special preparation should be run from within a task group
pre: &test_setup
  - func: "fetch source"
  - func: "prepare resources"
  - func: "fix absolute paths"
  - func: "make files executable"
  - func: "install dependencies"
  - func: "locate PHP binaries"
  - func: "fetch extension"
  - func: "install composer"
post: &test_teardown
  - func: "upload mo artifacts"
  - func: "upload test results"
  - func: "delete serverless instance"
  - func: "stop load balancer"
  - func: "stop mongo-orchestration"
  - func: "cleanup"

# Include files that contain various tasks, task groups, and build variant definitions
include:
  - filename: .evergreen/config/functions.yml

  - filename: .evergreen/config/build-task-groups.yml
  - filename: .evergreen/config/build-variants.yml

  - filename: .evergreen/config/test-tasks.yml
  - filename: .evergreen/config/test-task-groups.yml
  - filename: .evergreen/config/test-variants.yml

  # Automatically generated files
  - filename: .evergreen/config/build/build-php-8.2.yml
  - filename: .evergreen/config/build/build-php-8.1.yml
  - filename: .evergreen/config/build/build-php-8.0.yml
  - filename: .evergreen/config/build/build-php-7.4.yml
  - filename: .evergreen/config/test/local-latest.yml
  - filename: .evergreen/config/test/local-rapid.yml
  - filename: .evergreen/config/test/local-7.0.yml
  - filename: .evergreen/config/test/local-6.0.yml
  - filename: .evergreen/config/test/local-5.0.yml
  - filename: .evergreen/config/test/local-4.4.yml
  - filename: .evergreen/config/test/local-4.2.yml
  - filename: .evergreen/config/test/local-4.0.yml
  - filename: .evergreen/config/test/local-3.6.yml
  - filename: .evergreen/config/test/load-balanced-latest.yml
  - filename: .evergreen/config/test/load-balanced-rapid.yml
  - filename: .evergreen/config/test/load-balanced-7.0.yml
  - filename: .evergreen/config/test/load-balanced-6.0.yml
  - filename: .evergreen/config/test/load-balanced-5.0.yml
  - filename: .evergreen/config/test/require-api-version-latest.yml
  - filename: .evergreen/config/test/require-api-version-rapid.yml
  - filename: .evergreen/config/test/require-api-version-7.0.yml
  - filename: .evergreen/config/test/require-api-version-6.0.yml
  - filename: .evergreen/config/test/require-api-version-5.0.yml
