# $schema: ../schema.json
name: $search
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/search/'
type:
    - stage
encode: object
description: |
    Performs a full-text search of the field or fields in an Atlas collection.
    NOTE: $search is only available for MongoDB Atlas clusters, and is not available for self-managed deployments.
arguments:
    -
        name: operator
        mergeObject: true
        type:
            - searchOperator
        description: |
            Operator to search with.  You can provide a specific operator or use
            the compound operator to run a compound query with multiple operators.
    -
        name: index
        optional: true
        type:
            - string
        description: |
            Name of the Atlas Search index to use. If omitted, defaults to "default".
    -
        name: highlight
        optional: true
        type:
            # @todo support "highlight" type object
            # https://www.mongodb.com/docs/atlas/atlas-search/highlighting/
            - object
        description: |
            Specifies the highlighting options for displaying search terms in their original context.
    -
        name: concurrent
        optional: true
        type:
            - bool
        description: |
            Parallelize search across segments on dedicated search nodes.
            If you don't have separate search nodes on your cluster, 
            Atlas Search ignores this flag. If omitted, defaults to false.
    -
        name: count
        optional: true
        type:
            - object
        description: |
            Document that specifies the count options for retrieving a count of the results.
    -
        name: searchAfter
        optional: true
        type:
            - string
        description: |
            Reference point for retrieving results. searchAfter returns documents starting immediately following the specified reference point.
    -
        name: searchBefore
        optional: true
        type:
            - string
        description: |
            Reference point for retrieving results. searchBefore returns documents starting immediately before the specified reference point.
    -
        name: scoreDetails
        optional: true
        type:
            - bool
        description: |
            Flag that specifies whether to retrieve a detailed breakdown of the score for the documents in the results. If omitted, defaults to false.
    -
        name: sort
        optional: true
        type:
            - object
        description: |
            Document that specifies the fields to sort the Atlas Search results by in ascending or descending order.
    -
        name: returnStoredSource
        optional: true
        type:
            - bool
        description: |
            Flag that specifies whether to perform a full document lookup on the backend database or return only stored source fields directly from Atlas Search.
    -
        name: tracking
        optional: true
        type:
            - object
        description: |
            Document that specifies the tracking option to retrieve analytics information on the search terms.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/query-syntax/#aggregation-variable'
        pipeline:
            -
                $search:
                    near:
                        path: 'released'
                        origin: !bson_utcdatetime '2011-09-01T00:00:00.000+00:00'
                        pivot: 7776000000
            -
                $project:
                    _id: 0
                    title: 1
                    released: 1
            -
                $limit: 5
            -
                $facet:
                    docs: []
                    meta:
                        -
                            $replaceWith: '$$SEARCH_META'
                        -
                            $limit: 1
    -
        name: 'Date Search and Sort'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/sort/#date-search-and-sort'
        pipeline:
            -
                $search:
                    range:
                        path: 'released'
                        gt: !bson_utcdatetime '2010-01-01T00:00:00.000Z'
                        lt: !bson_utcdatetime '2015-01-01T00:00:00.000Z'
                    sort:
                        released: -1
            -
                $limit: 5
            -
                $project:
                    _id: 0
                    title: 1
                    released: 1
    -
        name: 'Number Search and Sort'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/sort/#number-search-and-sort'
        pipeline:
            -
                $search:
                    range:
                        path: 'awards.wins'
                        gt: 3
                    sort:
                        awards.wins: -1
            -
                $limit: 5
            -
                $project:
                    _id: 0
                    title: 1
                    awards.wins: 1
    -
        name: 'Sort by score'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/sort/#sort-by-score'
        pipeline:
            -
                $search:
                    text:
                        path: 'title'
                        query: 'story'
                    sort:
                        score:
                            $meta: 'searchScore'
                            order: 1
            -
                $limit: 5
            -
                $project:
                    _id: 0
                    title: 1
                    score:
                        $meta: 'searchScore'
    -
        name: 'Paginate results after a token'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/paginate-results/#search-after-the-reference-point'
        pipeline:
            -
                $search:
                    text:
                        path: 'title'
                        query: 'war'
                    sort:
                        score:
                            $meta: 'searchScore'
                        released: 1
                    searchAfter: 'CMtJGgYQuq+ngwgaCSkAjBYH7AAAAA=='
    -
        name: 'Paginate results before a token'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/paginate-results/#search-before-the-reference-point'
        pipeline:
            -
                $search:
                    text:
                        path: 'title'
                        query: 'war'
                    sort:
                        score:
                            $meta: 'searchScore'
                        released: 1
                    searchBefore: 'CJ6kARoGELqvp4MIGgkpACDA3U8BAAA='
    -
        name: 'Count results'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/counting/#count-results'
        pipeline:
            -
                $search:
                    near:
                        path: 'released'
                        origin: !bson_utcdatetime '2011-09-01T00:00:00.000+00:00'
                        pivot: 7776000000
                    count:
                        type: 'total'
            -
                $project:
                    meta: '$$SEARCH_META'
                    title: 1
                    released: 1
            -
                $limit: 2
    -
        name: 'Track Search terms'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/tracking/#examples'
        pipeline:
            -
                $search:
                    text:
                        query: 'summer'
                        path: 'title'
                    tracking:
                        searchTerms: 'summer'
            -
                $limit: 5
            -
                $project:
                    _id: 0
                    title: 1
    -
        name: 'Return Stored Source Fields'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/return-stored-source/#examples'
        pipeline:
            -
                $search:
                    text:
                        query: 'baseball'
                        path: 'title'
                    returnStoredSource: true
            -
                $match:
                    $or:
                        -
                            imdb.rating:
                                $gt: 8.2
                        -
                            imdb.votes:
                                $gte: 4500
            -
                $lookup:
                    from: 'movies'
                    localField: '_id'
                    foreignField: '_id'
                    as: 'document'
