# $schema: ../schema.json
name: $searchMeta
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/searchMeta/'
type:
    - stage
encode: object
description: |
    Returns different types of metadata result documents for the Atlas Search query against an Atlas collection.
    NOTE: $searchMeta is only available for MongoDB Atlas clusters running MongoDB v4.4.9 or higher, and is not available for self-managed deployments.
arguments:
    -
        name: operator
        mergeObject: true
        type:
            - searchOperator
        description: |
            Operator to search with.  You can provide a specific operator or use
            the compound operator to run a compound query with multiple operators.
    -
        name: index
        optional: true
        type:
            - string
        description: |
            Name of the Atlas Search index to use. If omitted, defaults to default.

    -
        name: count
        optional: true
        type:
            - object
        description: |
            Document that specifies the count options for retrieving a count of the results.
tests:
    -
        name: 'Example'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/query-syntax/#example'
        pipeline:
            -
                $searchMeta:
                    range:
                        path: 'year'
                        gte: 1998
                        lt: 1999
                    count:
                        type: 'total'

    -
        name: 'Year Facet'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/facet/#example-1'
        pipeline:
            - $searchMeta:
                  facet:
                      operator:
                          range:
                              path: 'year'
                              gte: 1980
                              lte: 2000
                      facets:
                          yearFacet:
                              type: 'number'
                              path: 'year'
                              boundaries:
                                  - 1980
                                  - 1990
                                  - 2000
                              default: 'other'

    -
        name: 'Date Facet'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/facet/#example-2'
        pipeline:
            -
                $searchMeta:
                    facet:
                        operator:
                            range:
                                path: 'released'
                                gte: !bson_utcdatetime '2000-01-01T00:00:00.000Z'
                                lte: !bson_utcdatetime '2015-01-31T00:00:00.000Z'
                        facets:
                            yearFacet:
                                type: 'date'
                                path: 'released'
                                boundaries:
                                    - !bson_utcdatetime '2000-01-01'
                                    - !bson_utcdatetime '2005-01-01'
                                    - !bson_utcdatetime '2010-01-01'
                                    - !bson_utcdatetime '2015-01-01'
                                default: 'other'

    -
        name: 'Metadata Results'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/facet/#examples'
        pipeline:
            -
                $searchMeta:
                    facet:
                        operator:
                            range:
                                path: 'released'
                                gte: !bson_utcdatetime '2000-01-01T00:00:00.000Z'
                                lte: !bson_utcdatetime '2015-01-31T00:00:00.000Z'
                        facets:
                            directorsFacet:
                                type: 'string'
                                path: 'directors'
                                numBuckets: 7
                            yearFacet:
                                type: 'number'
                                path: 'year'
                                boundaries:
                                    - 2000
                                    - 2005
                                    - 2010
                                    - 2015

    -
        name: 'Autocomplete Bucket Results through Facet Queries'
        link: 'https://www.mongodb.com/docs/atlas/atlas-search/autocomplete/#bucket-results-through-facet-queries'
        pipeline:
            -
                $searchMeta:
                    facet:
                        operator:
                            autocomplete:
                                path: 'title'
                                query: 'Gravity'
                        facets:
                            titleFacet:
                                type: 'string'
                                path: 'title'
