# $schema: ../schema.json
name: $vectorSearch
link: 'https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/'
type:
    - stage
encode: object
description: |
    The $vectorSearch stage performs an ANN or ENN search on a vector in the specified field.
arguments:
    -
        name: index
        type:
            - string
        description: |
            Name of the Atlas Vector Search index to use.
    -
        name: limit
        type:
            - int
        description: |
            Number of documents to return in the results. This value can't exceed the value of numCandidates if you specify numCandidates.
    -
        name: path
        type:
            - searchPath
        description: |
            Indexed vector type field to search.
    -
        name: queryVector
        type:
            - array # of numbers
        description: |
            Array of numbers that represent the query vector. The number type must match the indexed field value type.
    -
        name: exact
        optional: true
        type:
            - bool
        description: |
            This is required if numCandidates is omitted. false to run ANN search. true to run ENN search.
    -
        name: filter
        optional: true
        type:
            - query
        description: |
            Any match query that compares an indexed field with a boolean, date, objectId, number (not decimals), string, or UUID to use as a pre-filter.
    -
        name: numCandidates
        optional: true
        type:
            - int
        description: |
            This field is required if exact is false or omitted.
            Number of nearest neighbors to use during the search. Value must be less than or equal to (<=) 10000. You can't specify a number less than the number of documents to return (limit).

tests:
    -
        name: 'ANN Basic'
        link: 'https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/#ann-examples'
        pipeline:
            -
                $vectorSearch:
                    index: 'vector_index'
                    path: 'plot_embedding'
                    queryVector: [-0.0016261312, -0.028070757, -0.011342932] # skip other numbers, not relevant to the test
                    numCandidates: 150
                    limit: 10
            -
                $project:
                    _id: 0
                    plot: 1
                    title: 1
                    score:
                        $meta: 'vectorSearchScore'

    -
        name: 'ANN Filter'
        link: 'https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/#ann-examples'
        pipeline:
            -
                $vectorSearch:
                    index: 'vector_index'
                    path: 'plot_embedding'
                    filter:
                        $and:
                            -
                                year:
                                    $lt: 1975
                    queryVector: [0.02421053, -0.022372592, -0.006231137] # skip other numbers, not relevant to the test
                    numCandidates: 150
                    limit: 10
            -
                $project:
                    _id: 0
                    title: 1
                    plot: 1
                    year: 1
                    score:
                        $meta: 'vectorSearchScore'

    -
        name: 'ENN'
        link: 'https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/#enn-examples'
        pipeline:
            -
                $vectorSearch:
                    index: 'vector_index'
                    path: 'plot_embedding'
                    queryVector: [-0.006954097, -0.009932499, -0.001311474] # skip other numbers, not relevant to the test
                    exact: true
                    limit: 10
            -
                $project:
                    _id: 0
                    plot: 1
                    title: 1
                    score:
                        $meta: 'vectorSearchScore'
