# $schema: ../schema.json
name: $bitsAllClear
category:
    - 'Bitwise Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAllClear/'
type:
    - query
encode: single
description: |
    Matches numeric or binary values in which a set of bit positions all have a value of 0.
arguments:
    -
        name: bitmask
        type:
            - int
            - binData
            - array # of int
