# $schema: ../schema.json
name: $elemMatch
category:
    - 'Projection Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/elemMatch/'
type:
    - filter
    - projection
encode: object
description: |
    Projects the first element in an array that matches the specified $elemMatch condition.
arguments:
    -
        name: queries
        type:
            - query
