# $schema: ../schema.json
name: $geoIntersects
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/geoIntersects/'
type:
    - fieldQuery
encode: object
description: |
    Selects geometries that intersect with a GeoJSON geometry. The 2dsphere index supports $geoIntersects.
arguments:
    -
        name: geometry
        mergeObject: true
        type:
            - geometry
tests:
    -
        name: 'Intersects a Polygon'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/geoIntersects/#intersects-a-polygon'
        pipeline:
            -
                $match:
                    loc:
                        $geoIntersects:
                            $geometry:
                                type: 'Polygon'
                                coordinates:
                                    -
                                        - [ 0, 0 ]
                                        - [ 3, 6 ]
                                        - [ 6, 1 ]
                                        - [ 0, 0 ]
    -
        name: 'Intersects a Big Polygon'
        link: 'https://www.mongodb.com/docs/manual/reference/operator/query/geoIntersects/#intersects-a--big--polygon'
        pipeline:
            -
                $match:
                    loc:
                        $geoIntersects:
                            $geometry:
                                type: 'Polygon'
                                coordinates:
                                    -
                                        - [ -100, 60 ]
                                        - [ -100, 0 ]
                                        - [ -100, -60 ]
                                        - [ 100, -60 ]
                                        - [ 100, 60 ]
                                        - [ -100, 60 ]
                                crs:
                                    type: 'name'
                                    properties:
                                        name: 'urn:x-mongodb:crs:strictwinding:EPSG:4326'
