# $schema: ../schema.json
name: $gte
category:
    - 'Comparison Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/gte/'
type:
    - filter
encode: single
description: |
    Matches values that are greater than or equal to a specified value.
arguments:
    -
        name: value
        type:
            - any
