# $schema: ../schema.json
name: $minDistance
category:
    - 'Geospatial Geometry Specifiers'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/minDistance/'
type:
    - query
encode: single
description: |
    Specifies a minimum distance to limit the results of $near and $nearSphere queries. For use with 2dsphere index only.
arguments:
    -
        name: value
        type:
            - int
            - double
