# $schema: ../schema.json
name: $
category:
    - 'Projection Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/projection/positional/'
type:
    - query
encode: object
description: |
    Projects the first element in an array that matches the query condition.
