# $schema: ../schema.json
name: $regex
category:
    - 'Evaluation Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/regex/'
type:
    - filter
encode: single
description: |
    Selects documents where values match a specified regular expression.
arguments:
    -
        name: regex
        type:
            - regex
