# $schema: ../schema.json
name: $addToSet
category:
    - Accumulators
    - 'Window Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/addToSet/'
type:
    - Accumulator
encode: single
description: |
    Returns an array of unique expression values for each group. Order of the array elements is undefined.
    Changed in version 5.0: Available in the $setWindowFields stage.
arguments:
    -
        name: expression
        type:
            - expression
            - fieldPath
