# $schema: ../schema.json
name: $documentNumber
category:
    - 'Window Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/documentNumber/'
type:
    - resolvesToInt
encode: object
description: |
    Returns the position of a document (known as the document number) in the $setWindowFields stage partition. Ties result in different adjacent document numbers.
    New in version 5.0.
