# $schema: ../schema.json
name: $toDate
category:
    - 'Date Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/toDate/'
type:
    - resolvesToDate
encode: single
description: |
    Converts value to a Date.
    New in version 4.0.
arguments:
    -
        name: expression
        type:
            - expression
