# $schema: ../schema.json
name: $top
category:
    - Accumulators
    - 'Window Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/top/'
type:
    - Accumulator
encode: object
description: |
    Returns the top element within a group according to the specified sort order.
    New in version 5.2.

    Available in the $group and $setWindowFields stages.
arguments:
    -
        name: sortBy
        type:
            - SortSpec
        description: |
            Specifies the order of results, with syntax similar to $sort.
    -
        name: output
        type:
            - expression
        description: |
            Represents the output for each element in the group and can be any expression.
