# $schema: ../schema.json
name: $type
category:
    - 'Type Expression Operator'
link: 'https://www.mongodb.com/docs/manual/reference/operator/aggregation/type/'
type:
    - resolvesToString
encode: single
description: |
    Return the BSON data type of the field.
arguments:
    -
        name: expression
        type:
            - expression
