# This file is generated automatically - please edit the "templates/test-variant/phpc.yml" template file instead.
buildvariants:
  # Variants with different PHPC versions
  - name: test-debian12-php-8.3-phpc-next-stable
    tags: ["test", "debian", "x64", "php8.3", "pr", "tag"]
    display_name: "Test: Debian 12, PHP 8.3, PHPC next-stable"
    run_on: debian12-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian12"
      FETCH_BUILD_TASK: "build-php-8.3-next-stable"
      PHP_VERSION: "8.3"
    depends_on:
      - variant: "build-debian12"
        name: "build-php-8.3-next-stable"
    tasks:
      - ".standalone .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".replicaset .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".sharded .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".loadbalanced .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - "test_serverless_task_group"
      - "test_serverless_proxy_task_group"
      - "test-atlas-data-lake"

  - name: test-debian12-php-8.3-phpc-next-minor
    tags: ["test", "debian", "x64", "php8.3"]
    display_name: "Test: Debian 12, PHP 8.3, PHPC next-minor"
    run_on: debian12-small
    expansions:
      FETCH_BUILD_VARIANT: "build-debian12"
      FETCH_BUILD_TASK: "build-php-8.3-next-minor"
      PHP_VERSION: "8.3"
    depends_on:
      - variant: "build-debian12"
        name: "build-php-8.3-next-minor"
    tasks:
      - ".standalone .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".replicaset .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".sharded .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - ".loadbalanced .local !.csfle !.4.0 !.4.2 !.4.4 !.5.0 !.6.0"
      - "test_serverless_task_group"
      - "test_serverless_proxy_task_group"
      - "test-atlas-data-lake"
