# $schema: ../schema.json
name: $bitsAllSet
category:
    - 'Bitwise Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/bitsAllSet/'
type:
    - query
encode: single
description: |
    Matches numeric or binary values in which a set of bit positions all have a value of 1.
arguments:
    -
        name: bitmask
        type:
            - int
            - binData
            - list<int>
