# $schema: ../schema.json
name: $comment
category:
    - 'Miscellaneous Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/comment/'
type:
    - expression
encode: single
description: |
    Adds a comment to a query predicate.
arguments:
    -
        name: comment
        type:
            - string
