# $schema: ../schema.json
name: $exists
category:
    - 'Element Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/exists/'
type:
    - Query
encode: single
description: |
    Matches documents that have the specified field.
arguments:
    -
        name: exists
        type:
            - bool
