# $schema: ../schema.json
name: $meta
category:
    - 'Projection Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/meta/'
type:
    - projection
encode: object
description: |
    Projects the available per-document metadata.
