# $schema: ../schema.json
name: $not
category:
    - 'Logical Query Operators'
link: 'https://www.mongodb.com/docs/manual/reference/operator/query/not/'
type:
    - Query
encode: single
description: |
    Inverts the effect of a query expression and returns documents that do not match the query expression.
arguments:
    -
        name: expression
        type:
            - Query
