name: "Static Analysis"

on:
  merge_group:
  pull_request:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"

env:
  PHP_VERSION: "8.2"
  DRIVER_VERSION: "stable"

jobs:
  psalm:
    name: "Psalm"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: "mongodb-${{ env.DRIVER_VERSION }}"
          key: "extcache-v1"

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "mongodb-${{ env.DRIVER_VERSION }}"
          php-version: "${{ env.PHP_VERSION }}"
          tools: "cs2pr"

      - name: "Show driver information"
        run: "php --ri mongodb"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@3.0.0"
        with:
          composer-options: "--no-suggest"

      - name: "Run Psalm"
        run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc) --report=psalm.sarif"

      - name: "Run Rector"
        run: "vendor/bin/rector --ansi --dry-run"

      - name: "Upload Psalm report"
        uses: actions/upload-artifact@v4
        with:
          name: psalm.sarif
          path: psalm.sarif
