name: "Static Analysis"

on:
  pull_request:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
    paths-ignore:
      - "docs/**"

jobs:
  psalm:
    name: "Psalm"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"
        driver-version:
          - "mongodb/mongo-php-driver@master"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: "mongodb-${{ matrix.driver-version }}"
          key: "extcache-v1"

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "mongodb-${{ matrix.driver-version }}"
          php-version: "${{ matrix.php-version }}"
          tools: "cs2pr"

      - name: "Show driver information"
        run: "php --ri mongodb"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "--no-suggest"

      - name: "Run Psalm"
        run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc)"

      - name: "Run Rector"
        run: "vendor/bin/rector --ansi --dry-run"
