name: "Static Analysis"

on:
  merge_group:
  pull_request:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
    tags:
      - "*"

env:
  PHP_VERSION: "8.2"
  DRIVER_VERSION: "stable"

jobs:
  psalm:
    name: "Psalm"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup"
        uses: "./.github/actions/setup"
        with:
          php-version: ${{ env.PHP_VERSION }}
          driver-version: ${{ env.DRIVER_VERSION }}

      - name: "Run Psalm"
        run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc) --report=psalm.sarif"

      - name: "Upload SARIF report"
        uses: "github/codeql-action/upload-sarif@v3"
        with:
          sarif_file: psalm.sarif

  rector:
    name: "Rector"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup"
        uses: "./.github/actions/setup"
        with:
          php-version: ${{ env.PHP_VERSION }}
          driver-version: ${{ env.DRIVER_VERSION }}

      - name: "Run Rector"
        run: "vendor/bin/rector --ansi --dry-run"
