name: "Tests"

on:
  merge_group:
  pull_request:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - "v*.*"
      - "master"
      - "feature/*"
    paths-ignore:
      - "docs/**"

env:
  DRIVER_VERSION: "stable"

jobs:
  phpunit:
    name: "PHPUnit tests"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu-20.04"
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        mongodb-version:
          - "4.4"
        topology:
          - "server"
        include:
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "6.0"
            topology: "replica_set"
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "6.0"
            topology: "sharded_cluster"
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "5.0"
            topology: "server"
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "4.4"
            topology: "replica_set"
          - os: "ubuntu-20.04"
            php-version: "8.0"
            mongodb-version: "4.4"
            topology: "sharded_cluster"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@master
        with:
          version: ${{ matrix.mongodb-version }}
          topology: ${{ matrix.topology }}

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: "mongodb-${{ env.DRIVER_VERSION }}"
          key: "extcache-v1"

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "pecl"
          extensions: "mongodb-${{ env.DRIVER_VERSION }}"
          coverage: "none"
          ini-values: "zend.assertions=1"

      - name: "Show driver information"
        run: "php --ri mongodb"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@3.0.0"
        with:
          # Revert when psalm supports PHP 8.4
          # composer-options: "--no-suggest"
          composer-options: "--no-suggest ${{ matrix.php-version == '8.4' && '--ignore-platform-req=php+' || '' }}"


      - name: "Run PHPUnit"
        run: "vendor/bin/simple-phpunit -v"
        env:
          SYMFONY_DEPRECATIONS_HELPER: 999999
          MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
