name: "Tests"

on:
  merge_group:
  pull_request:
    branches:
      - "v*.*"
      - "feature/*"
  push:
    branches:
      - "v*.*"
      - "feature/*"

env:
  # TODO: change to "stable" once 2.0.0 is released
  # DRIVER_VERSION: "stable"
  DRIVER_VERSION: "mongodb/mongo-php-driver@v2.x"

jobs:
  phpunit:
    name: "PHPUnit tests"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu-20.04"
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        mongodb-version:
          - "4.4"
        topology:
          - "server"
        include:
          - os: "ubuntu-20.04"
            php-version: "8.1"
            mongodb-version: "6.0"
            topology: "replica_set"
          - os: "ubuntu-20.04"
            php-version: "8.1"
            mongodb-version: "6.0"
            topology: "sharded_cluster"
          - os: "ubuntu-20.04"
            php-version: "8.1"
            mongodb-version: "5.0"
            topology: "server"
          - os: "ubuntu-20.04"
            php-version: "8.1"
            mongodb-version: "4.4"
            topology: "replica_set"
          - os: "ubuntu-20.04"
            php-version: "8.1"
            mongodb-version: "4.4"
            topology: "sharded_cluster"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2
          submodules: true

      - id: setup-mongodb
        uses: mongodb-labs/drivers-evergreen-tools@81c6b49dd61e833229d750084f9f3c71b31acd8d
        with:
          version: ${{ matrix.mongodb-version }}
          topology: ${{ matrix.topology }}

      - name: "Setup"
        uses: "./.github/actions/setup"
        with:
          php-version: ${{ matrix.php-version }}
          driver-version: ${{ env.DRIVER_VERSION }}
          php-ini-values: "zend.assertions=1"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
        env:
          MONGODB_URI: ${{ steps.setup-mongodb.outputs.cluster-uri }}
